### ISSUE TITLE
主要是docker问题

### ISSUE THREAD

**Issue by MonkWang** [qiuyuhome/candy#13]
@zhuwannian @qiuyuhome @hufangfang1 @hhyun @phpdump  如果一个小团队的用的docker，是不是还需要一个专有的docker账号，大家伙是从一个docker账户中拉取相同的环境
为了统一开发环境，是不是需要先在docker里安装一个linux镜像，之后再在这个镜像中安装nginx/php/mysql/redis的容器，
镜像，容器，仓库，这三个概念大家都是如何去区别的

**Comment by qiuyimo** [comment]
请先阅读 #9 #10 

然后再发表 issue

**Comment by qiuyimo** [comment]
# 下次3个问题要发3个 issue.

### 问题1: 如果一个小团队的用的docker，是不是还需要一个专有的docker账号
dockerhub 上别人发表的可以直接下载. 无需同同一个账号. 这些概念都与 git 或者 composer 类似. 

### 问题2: 为了统一开发环境，是不是需要先在docker里安装一个linux镜像，之后再在这个镜像中安装nginx/php/mysql/redis的容器
如果这个服务依赖系统, 那么就得用一个系统的镜像作为基础镜像. 

### 问题3: 镜像，容器，仓库，这三个概念大家都是如何去区别的
参考 [手册中的基本概念](https://yeasy.gitbooks.io/docker_practice/content/basic_concept/)

简单来说, 容器是镜像运行的实例, 类似于类和对象的关系. hub.docker.com 就是仓库, 也可以自己搭建私有仓库, 熟悉git, 仓库这个概念就没问题了.

**Comment by qiuyimo** [comment]
你的这个 issue 标题,  哎. 等于没写.

**Comment by hufangfang1** [comment]
## 我的理解

1. 环境搭建大部分都是基于线上公有仓库，都可以拉取

2. 我们的开发环境是`nginx`、`php`、`mysql`等，只要他们的镜像一样，由镜像生成的容器就一样，最终的环境就一样

3. 三者关系

- 仓库

  >仓库是存放镜像的地方，每个电脑只要安装了 docker 都有一个仓库，仓库里面的镜像可以从线上 pull 也可以 build 自己创建

- 镜像

  >镜像是容器运行的基础，是用来生成容器的

- 容器

  >容器是镜像的实例，是直接用来提供服务的，一个镜像可以生成多个容器，由同一个镜像生成的容器功能是一样的
