### ISSUE TITLE
每个人要在pc端和手机端安装一个邮件软件, 以便接收github发送的消息通知.

### ISSUE THREAD

**Issue by qiuyimo** [qiuyuhome/candy#14]
每个人要在pc端和手机端安装一个邮件软件, 以便接收github发送的消息通知.

## mac

推荐安装网易的 `邮件大师`, 然后关联账号就可以了. 
![image](https://user-images.githubusercontent.com/17526777/37556255-4a584e18-2a2e-11e8-9e42-93bbf1768d70.png)

## windows

也有 邮件大师, 功能应该一样的. 

## 手机

iphone 自带的 `邮件app` 也不错.

**Comment by zhuwannian** [comment]
iphone 自带的 邮件app  绑定163邮箱
https://jingyan.baidu.com/article/5d368d1ed446f53f61c0576f.html
