### ISSUE TITLE
完结的问题, 发表这要关闭这个 issue

### ISSUE THREAD

**Issue by qiuyimo** [qiuyuhome/candy#16]
如果发表的 issue 已经被别人解决(自己解决的请把答案公布出来), 然后关闭这个 issue. 如果有必要, 可以再次开启. 

![image](https://user-images.githubusercontent.com/17526777/37556980-bf11d760-2a38-11e8-87cf-6f93cfea6d37.png)

**Comment by zhuwannian** [comment]
ok
