### ISSUE TITLE
团队名称

### ISSUE THREAD

**Issue by qiuyimo** [qiuyuhome/candy#4]
要搞事情, 不知道搞什么.

最后我家老大说, 那你们的团队可以叫 **搞事情团队**.

老王又给起了一个英文的团队名称, **GSQ TEAM**.

现在申请投票啊. 

团队的中文名称: 搞事情团队
团队的英文名称: GSQ TEAM

**Comment by ZhanYinghui1** [comment]
咱们团队名字叫 **都汇**  怎么样？都（du一声）汇，，是 都（dou）会 的音译，，意思是咱们团队啥都会做，啥都要学习，也意味着将在北京首都汇聚更多的人才互相学习 @qiuyuhome @hufangfang1 @hhyun @phpdump @MonkWang

**Comment by ZhanYinghui1** [comment]
英文名称 dooTeam

**Comment by qiuyimo** [comment]
大家投票吧. @MonkWang @hufangfang1 @hhyun @ZhanYinghui1
