### ISSUE TITLE
共同进步, 协同学习的方案

### ISSUE THREAD

**Issue by qiuyimo** [qiuyuhome/candy#5]
# 概述
共同进步, 协同学习的方案, 跟项目无关, 是指大家共同拟定一个小的计划, 然后大家在指定的时间内, 学习了解新的技术知识点, 最后在把自己的理解共享出来. 达到协同学习的目的. 

## 举例
大家都学习一下 `laravel` 的源码, 以及 `laravel` 和 `ThinkPHP` 区别. 学习时间为5天, 5天后, 晚上9点到10点之间语音讨论遇到的问题和交流经验. 

## 实现方式
写技术博客或者笔记. 
*推荐都弄一个 `gitpage` 的免费博客. *

## 目的
在较短的时间内, 了解新的知识点. 

> 在一个团队内, 就应该充分的利用团队的优势, 人多力量大, 共同学习比自己一个人研究更效率. 

大家还有什么好的方案. 留言讨论吧.

**Comment by hufangfang1** [comment]
很不错的提议，我觉得结合项目会比较好，比如项目中遇到的知识点我们不会可以列到计划里面，学习讨论之后可以马上用上，加深理解记忆
