### ISSUE TITLE
2018-03-12 至 2018-03-14 三天时间初步了解 docker

### ISSUE THREAD

**Issue by qiuyimo** [qiuyuhome/candy#7]
# 初步整体了解 docker

## 时间安排
2018-03-12 至 2018-03-14 三天时间

## 目的
整体性的初步了解 docker, 对 docker 有初步的认识, 找出 docker 中难点及知识点供后续学习做准备. 

## 要求
做好博客记录, 列出 docker 中的知识点及难点, 且规划处每个知识点的学习时间.

## 团队聚集讨论
2018-03-15日, 晚上大概9点左右. 一起探讨总结.

## docker 官方文档中文版
https://octowhale.gitbooks.io/doc2cn_docker/content/

## docker 中文手册
https://yeasy.gitbooks.io/docker_practice/content/install/mac.html

## docker 问答录 (100问)
https://blog.lab99.org/post/docker-2016-07-14-faq.html#wei-shi-me-shuo-bu-yao-shi-yong-import-export-save-load-commit-lai-gou-jian-jing-xiang

## LNMP - Docker 多容器间协作互连
https://github.com/twang2218/docker-lnmp

## dnmp
https://github.com/yeszao/dnmp

学习过程中, 有好的资源或者教程, 共享出来.

**Comment by qiuyimo** [comment]
大家把自己记录的关于 `docker` 博客文章的 `URL`, 发到这个 `issues` 里. 方便大家查看.

**Comment by hufangfang1** [comment]
我对docker的大致了解
http://www.hffhom.com/2018/03/15/docker/

**Comment by hufangfang1** [comment]
## LNMP Dockerfile
用docker构建一个多层镜像每层一个服务
https://github.com/liufee/docker

**Comment by qiuyimo** [comment]
我暂时没搞定的问题.
http://www.qiuyuhome.com/2018/03/10/docker/

**Comment by MonkWang** [comment]
这里似乎是一个国内的一个docker的权威网站
https://www.docker-cn.com

**Comment by qiuyimo** [comment]
我发现的比较好的 `docker` 搭建 `lnmp` 环境的项目. 
https://github.com/khs1994-docker/lnmp
